### ISSUE TITLE
Repository default branch (develop vs master)

### ISSUE THREAD

**Issue by atdrago** [podverse/podcast-feed-parser#12]
Hey there!

I noticed that this repository's default branch is `develop`, but it also has a `master` branch, which is what is published on NPM. Is there a purpose for the `develop` branch, or would you be interested in changing the default to `master` and deleting `develop`?

Thanks!

**Comment by mitchdowney** [comment]
@atdrago finally seeing this 😅 

We want to get rid of this library sooner or later and replace it with podcast partytime in the mobile app, but we're still using podcast-feed-parser to parse local "add by RSS" feeds.

Anyway, I switched the default branch. Thanks for letting us know.
